name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        version:
          - 1.82.0
          - stable
          - beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v7
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.version }}
    - name: Run tests
      run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt
    - name: Clippy lint
      run: cargo clippy --all-features --all-targets -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Deadlinks
      run: |
        cargo install cargo-deadlinks
        cargo doc
        cargo deadlinks -v --check-http
